apiVersion: v1
kind: Service
metadata:
  name: ecap-api-service
  namespace: ecap
spec:
  selector:
    app: ecap-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
